/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class menu_absenGuru extends javax.swing.JInternalFrame {
private Connection con = new koneksi().getConnection();
private DefaultTableModel tabmode;
PreparedStatement ps;
ResultSet rs;
    /**
     * Creates new form menu_loginGuru
     */
    public menu_absenGuru() {
        initComponents();
        
        datatable();
        aktif();
        kosong();
    }
    protected void datatable(){ 
        // 1. Definisikan header/judul kolom (4 Kolom utama)
        String[] baris = {"Kode Guru", "Tanggal", "Kehadiran", "Keterangan"};

        // 2. Buat Custom DefaultTableModel agar kolom ke-3 (Kehadiran) menjadi Checkbox
        tabmode = new DefaultTableModel(null, baris) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                // Index 2 adalah kolom "Kehadiran" (Dimulai dari 0, 1, 2)
                if (columnIndex == 2) { 
                    return Boolean.class; 
                }
                return super.getColumnClass(columnIndex);
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                // Hanya kolom index 2 (Kehadiran) dan index 3 (Keterangan) yang bisa diubah di tabel
                return column == 2 || column == 3; 
            }
        };

        tblguru.setModel(tabmode);

        try {
            // Query mengunci data berdasarkan guru yang sedang login
            String sql = "SELECT g.kd_guru, a.tgl, a.kehadiran, a.keterangan " +
                         "FROM guru g " +
                         "LEFT JOIN tbl_absen_guru a ON g.kd_guru = a.kd_guru " +
                         "WHERE g.kd_guru = ?"; 

            PreparedStatement stat = con.prepareStatement(sql);
            
            // --- CUKUP GANTI BAGIAN INI ---
            // Mengambil langsung Kode Guru yang aktif dari GuruSession
            stat.setString(1, GuruSession.getKdGuru()); 
            
            ResultSet hasil = stat.executeQuery();

            // Bersihkan baris lama sebelum load data baru
            tabmode.setRowCount(0);

            while (hasil.next()) {
                String kdGuru = hasil.getString("kd_guru");
                String tgl = hasil.getString("tgl") != null ? hasil.getString("tgl") : "-";
                
                int statusDb = hasil.getInt("kehadiran");
                boolean isHadir = (statusDb == 1); 
                
                String keterangan = hasil.getString("keterangan") != null ? hasil.getString("keterangan") : "";

                Object[] data = {
                    kdGuru,
                    tgl,
                    isHadir,      
                    keterangan    
                };
                tabmode.addRow(data);
            }

        } catch (Exception e) {
            e.printStackTrace(); 
            JOptionPane.showMessageDialog(this, "Gagal memuat data tabel: " + e.getMessage());
        }   
    }

       
        
    protected void aktif(){
        tglTemu.requestFocus();
    }
    
    protected void kosong(){
        jTemu.setValue(1);
        tglTemu.setDate(new Date());

    }
    
    public void cetak() {
        try{
            String path="./src/report/nota.jasper";
            HashMap parameter = new HashMap();
            String guruLogin = GuruSession.getKdGuru();
            System.out.println("=== DEBUG LOG === Kode Guru dari Session: " + guruLogin); 
            parameter.put("paramKdGuru", guruLogin); 
            JasperPrint print = JasperFillManager.fillReport(path, parameter,con);
            JasperViewer.viewReport(print, false);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(rootPane,"Dokumen tidak ada" +ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblguru = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tglTemu = new com.toedter.calendar.JDateChooser();
        jTemu = new javax.swing.JSpinner();
        bbatal = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bprint = new javax.swing.JButton();

        tblguru.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblguru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblguru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblguruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblguru);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Pertemuan", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(1, 1, 1))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(1, 1, 1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Tanggal  : ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Pertemuan ke- : ");

        jTemu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTemu.setModel(new javax.swing.SpinnerNumberModel(1, 1, 48, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(tglTemu, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTemu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(tglTemu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTemu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bbatal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        bsimpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Absensi Guru");

        bprint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bprint.setText("PRINT");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bprint, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bbatal)
                    .addComponent(bprint))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblguruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblguruMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblguruMouseClicked

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // Memunculkan dialog konfirmasi (opsional, tapi disarankan)
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Batal melakukan absensi? Semua isian dan centang akan dikosongkan.",
            "Konfirmasi Batal",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            // Panggil method yang sudah Anda buat untuk mereset tampilan
            kosong();     // Mengosongkan textfield dan tanggal
            datatable();  // Me-refresh tabel agar semua checkbox kembali kosong

            JOptionPane.showMessageDialog(this, "Form berhasil dibersihkan.", "Batal", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bbatalActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        if (tglTemu.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Pilih tanggal pertemuan terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int pertemuan_ke = (Integer) jTemu.getValue();
        if (pertemuan_ke <= 0) {
            JOptionPane.showMessageDialog(this, "Pertemuan tidak boleh 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Ambil Data Model dari JTable
        DefaultTableModel model = (DefaultTableModel) tblguru.getModel();
        int jumlahBaris = model.getRowCount();

        if (jumlahBaris == 0) {
            JOptionPane.showMessageDialog(this, "Tabel data guru masih kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Prompt Dialog Konfirmasi
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin data kehadiran sudah benar dan ingin disimpan?",
            "Konfirmasi Simpan",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

        if (konfirmasi != JOptionPane.YES_OPTION) {
            return; 
        }

        // 4. Konversi format tanggal ke SQL Date
        java.sql.Date sqlDate = new java.sql.Date(tglTemu.getDate().getTime());

try {
    // UPDATE: Query disesuaikan persis dengan 5 kolom asli di database (id_absen otomatis AUTO_INCREMENT)
    String sql = "INSERT INTO tbl_absen_guru (kd_guru, tgl, kehadiran, keterangan) " +
                 "VALUES (?, ?, ?, ?) " +
                 "ON DUPLICATE KEY UPDATE kehadiran = VALUES(kehadiran), keterangan = VALUES(keterangan)";
                 
    PreparedStatement pst = con.prepareStatement(sql);

    // 5. Perulangan membaca baris JTable
    for (int i = 0; i < jumlahBaris; i++) {
        String kdGuru = model.getValueAt(i, 0).toString();

        // Kolom ke-2 (Index 2) adalah Boolean Checkbox Kehadiran
        Object objKehadiran = model.getValueAt(i, 2);
        boolean isChecked = (objKehadiran != null && (Boolean) objKehadiran);
        int status_hadir = isChecked ? 1 : 0; // Masuk ke int(1) di database

        // Kolom ke-3 (Index 3) adalah String Keterangan
        Object objKeterangan = model.getValueAt(i, 3);
        String keterangan = (objKeterangan != null) ? objKeterangan.toString() : "";

        // PEMETAAN BARU (Wajib Berurutan):
        pst.setString(1, kdGuru);       // Mengisi kd_guru (varchar)
        pst.setDate(2, sqlDate);        // Mengisi tgl (date)
        pst.setInt(3, status_hadir);    // Mengisi kehadiran (int)
        pst.setString(4, keterangan);   // Mengisi keterangan (varchar)

        pst.addBatch(); 
    }

    // 6. Eksekusi batch
    pst.executeBatch();

    JOptionPane.showMessageDialog(this, "Data absensi guru berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

    // 7. Bersihkan dan segarkan form
    kosong();
    

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal menyimpan data absensi:\n" + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
}
    
        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
        cetak();
    }//GEN-LAST:event_bprintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bprint;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jTemu;
    private javax.swing.JTable tblguru;
    private com.toedter.calendar.JDateChooser tglTemu;
    // End of variables declaration//GEN-END:variables
}
