/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import static tampilan.frm_jadwal.txkg;

/**
 *
 * @author ACER
 */
public class menu_jadwal extends javax.swing.JInternalFrame {
private Connection con = new koneksi().getConnection();
private DefaultTableModel tabmode;
PreparedStatement ps;
ResultSet rs;
    /**
     * Creates new form menu_jadwal
     */
    public menu_jadwal() {
        initComponents();
        kosong();
        aktif();
        datatable();
        loadcombo();
        JSpinner.DateEditor timeEditor = new JSpinner.DateEditor(kjam, "HH:mm");
        kjam.setEditor(timeEditor);
        kjam.setValue(new java.util.Date());
    }
    
    protected void aktif(){
        txidm.requestFocus();
    }
    
    protected void kosong(){
        txidm.setText("");
        txmp.setText("");
        txkg.setText("");
        kjam.setValue(new java.util.Date());
        ckelas.setSelectedIndex(-1);
    }
    
    protected void datatable(){
        Object[] Baris = {"Id Mapel","Mata Pelajaran","Nama","Jam","Kelas"};
            tabmode = new DefaultTableModel(null,Baris);
            String cariitem = txcari.getText();
            try{
                String sql ="SELECT tbl_jadwal.id_mapel, tbl_jadwal.nama_mapel, tbl_jadwal.kd_guru, guru.nama, tbl_jadwal.jam, tbl_jadwal.kelas, tbl_kelas.kelas " +
                            "FROM tbl_jadwal " +
                            "JOIN guru ON tbl_jadwal.kd_guru = guru.kd_guru " +
                            "JOIN tbl_kelas ON tbl_jadwal.kelas = tbl_kelas.id_kelas " +
                            "WHERE tbl_jadwal.id_mapel LIKE '%"+cariitem+"%' OR tbl_jadwal.nama_mapel LIKE '%"+cariitem+"%' " +
                            "ORDER BY tbl_jadwal.id_mapel ASC";
                Statement stat = con.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()){
                    tabmode.addRow(new Object[]{
                        hasil.getString(1),
                        hasil.getString(2),
                        hasil.getString(4),
                        hasil.getString(5),
                        hasil.getString(7)
                    });
                }
                tbl_jadwal.setModel(tabmode);
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
            }
    }
    
    private void loadcombo() {
        try {
            // 1. Query untuk mengambil data unik dari tabel kelas
            String sql = "SELECT id_kelas FROM tbl_kelas";

            java.sql.Connection conn = (Connection)koneksi.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            // 2. Bersihkan item lama agar tidak double
            ckelas.removeAllItems(); 
            ckelas.addItem("-- Pilih Kelas --"); // Item pertama sebagai petunjuk

            // 3. Masukkan hasil query ke dalam Combo Box
            while(rs.next()) {
                ckelas.addItem(rs.getString("id_kelas"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Load Kelas: " + e.getMessage());
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txidm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txmp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txkg = new javax.swing.JTextField();
        btn_cguru = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        kjam = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        ckelas = new javax.swing.JComboBox<>();
        bsimpan = new javax.swing.JToggleButton();
        bedit = new javax.swing.JToggleButton();
        bhapus = new javax.swing.JToggleButton();
        bbatal = new javax.swing.JToggleButton();
        bkeluar = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        txcari = new javax.swing.JTextField();
        bcari = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jadwal = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("FORM JADWAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("ID Mapel :");

        txidm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Mata Pelajaran :");

        txmp.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Kode Guru :");

        txkg.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        btn_cguru.setText("Cari");
        btn_cguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cguruActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Jam :");

        kjam.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.AM_PM));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Kelas :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txidm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txkg, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cguru, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txmp)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kjam)
                            .addComponent(ckelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txidm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txkg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cguru, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(kjam, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(ckelas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, 620, 370));

        bsimpan.setBackground(new java.awt.Color(51, 255, 102));
        bsimpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 159, 49));

        bedit.setBackground(new java.awt.Color(255, 255, 51));
        bedit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bedit.setForeground(new java.awt.Color(255, 255, 255));
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });
        getContentPane().add(bedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 159, 49));

        bhapus.setBackground(new java.awt.Color(255, 0, 0));
        bhapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bhapus.setForeground(new java.awt.Color(255, 255, 255));
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        getContentPane().add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 159, 49));

        bbatal.setBackground(new java.awt.Color(255, 255, 255));
        bbatal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bbatal.setForeground(new java.awt.Color(204, 51, 0));
        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 159, 49));

        bkeluar.setBackground(new java.awt.Color(255, 255, 255));
        bkeluar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bkeluar.setForeground(new java.awt.Color(204, 51, 0));
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 159, 46));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Table Jadwal"));

        txcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txcariKeyPressed(evt);
            }
        });

        bcari.setBackground(new java.awt.Color(255, 255, 255));
        bcari.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bcari.setForeground(new java.awt.Color(0, 204, 204));
        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        tbl_jadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_jadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_jadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_jadwal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txcari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cguruActionPerformed
        pop_guru popup = new pop_guru(txkg);
        popup.loadData();
        popup.setLocationRelativeTo(this);
        popup.setVisible(true);
    }//GEN-LAST:event_btn_cguruActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm");
        String jamSimpan = sdf.format(kjam.getValue());
        String kls = ckelas.getSelectedItem().toString();
        String sql = "insert into tbl_jadwal values (?,?,?,?,?)";
        try{
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, txidm.getText());
            stat.setString(2, txmp.getText());
            stat.setString(3, txkg.getText());
            stat.setString(4, jamSimpan);
            stat.setString(5, kls);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txidm.requestFocus();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "error" + e.getMessage());
            e.printStackTrace();
        }
        datatable();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm");
        String jamSimpan = sdf.format(kjam.getValue());
        String kls = ckelas.getSelectedItem().toString();
        String sql = "update tbl_jadwal set nama_mapel=?, kd_guru=?, jam=?, kelas=? where id_mapel='"+txidm.getText()+"'";
        try {
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, txmp.getText());
            stat.setString(2, txkg.getText());
            stat.setString(3, jamSimpan);
            stat.setString(4, kls);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");

            kosong();
            txidm.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            e.printStackTrace();
        }
        datatable();
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) { // Jika user memilih tombol YES
            String sql = "delete from tbl_jadwal where id_mapel=?";
            try {
                PreparedStatement stat = con.prepareStatement(sql);

                // Ambil ID Mapel dari TextField sebagai acuan hapus
                stat.setString(1, txidm.getText());

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

                kosong();
                txidm.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
            datatable();
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void txcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txcariKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_txcariKeyPressed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
    }//GEN-LAST:event_bcariActionPerformed

    private void tbl_jadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_jadwalMouseClicked
        int baris = tbl_jadwal.getSelectedRow();
        txidm.setText(tbl_jadwal.getValueAt(baris, 0).toString());
        txmp.setText(tbl_jadwal.getValueAt(baris, 1).toString());
        txkg.setText(tbl_jadwal.getValueAt(baris, 2).toString());
        try {
            String jamTabel = tbl_jadwal.getValueAt(baris, 3).toString();
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("HH:mm");
            kjam.setValue(sdf.parse(jamTabel));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        ckelas.setSelectedItem(tbl_jadwal.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_tbl_jadwalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bbatal;
    private javax.swing.JToggleButton bcari;
    private javax.swing.JToggleButton bedit;
    private javax.swing.JToggleButton bhapus;
    private javax.swing.JToggleButton bkeluar;
    private javax.swing.JToggleButton bsimpan;
    private javax.swing.JToggleButton btn_cguru;
    private javax.swing.JComboBox<String> ckelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner kjam;
    private javax.swing.JTable tbl_jadwal;
    private javax.swing.JTextField txcari;
    private javax.swing.JTextField txidm;
    public static javax.swing.JTextField txkg;
    private javax.swing.JTextField txmp;
    // End of variables declaration//GEN-END:variables
}
